name: dataexplr
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - appnope=0.1.4
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - comm=0.2.2
  - debugpy=1.8.11
  - decorator=5.2.1
  - et_xmlfile=1.1.0
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.7.1
  - importlib-metadata=8.6.1
  - ipykernel=6.29.5
  - ipython=9.1.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - libcxx=14.0.6
  - libffi=3.4.4
  - libsodium=1.0.18
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openpyxl=3.1.5
  - openssl=3.5.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.0
  - platformdirs=4.3.7
  - prompt-toolkit=3.0.51
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - python=3.11.9
  - pyzmq=26.2.0
  - readline=8.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - stack_data=0.6.3
  - tk=8.6.14
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.13.2
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - pip:
      - absl-py==2.3.0
      - astunparse==1.6.3
      - attrs==25.3.0
      - beautifulsoup4==4.13.4
      - bs4==0.0.2
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - contourpy==1.3.2
      - cycler==0.12.1
      - dm-tree==0.1.9
      - docstring-parser==0.16
      - einops==0.8.1
      - etils==1.12.2
      - filetype==1.2.0
      - flatbuffers==25.2.10
      - fonttools==4.57.0
      - fsspec==2025.5.1
      - gast==0.6.0
      - google-pasta==0.2.0
      - googleapis-common-protos==1.70.0
      - grpcio==1.73.0
      - h5py==3.14.0
      - idna==3.7
      - immutabledict==4.2.1
      - importlib-resources==6.5.2
      - inflect==7.5.0
      - joblib==1.5.0
      - keras==3.10.0
      - kiwisolver==1.4.8
      - libclang==18.1.1
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - ml-dtypes==0.3.2
      - more-itertools==10.7.0
      - namex==0.1.0
      - numpy==1.26.4
      - opencv-python-headless==4.10.0.84
      - opt-einsum==3.4.0
      - optree==0.16.0
      - packaging==25.0
      - pandas==2.2.3
      - patsy==1.0.1
      - pillow==11.2.1
      - pillow-heif==0.22.0
      - promise==2.3
      - protobuf==4.25.8
      - pyarrow==20.0.0
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - pytz==2025.2
      - pyyaml==6.0.2
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - rich==14.0.0
      - roboflow==1.1.66
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - seaborn==0.13.2
      - simple-parsing==0.1.7
      - six==1.17.0
      - soupsieve==2.7
      - statsmodels==0.14.4
      - tabulate==0.9.0
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorflow[and-cuda]==2.16.2
      - tensorflow-datasets==4.9.9
      - tensorflow-metadata==1.17.1
      # - tensorflow-metal==1.2.0 Mac-specfic
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - toml==0.10.2
      - tqdm==4.67.1
      - typeguard==4.4.2
      - tzdata==2025.2
      - urllib3==2.4.0
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - xlrd==2.0.1
# prefix removed for portability; let Docker create the env under /opt/conda/envs/<name>
# prefix: /Users/mschramm/miniconda3/envs/dataexplr
